In [47]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
df = pd.read_csv('desktop/database1.csv')

In [48]:
X = df.drop(columns=['Date', 'Time', 'Type', 'Depth Error', 'Depth Seismic Stations', 'Magnitude'])
y = df['Magnitude']
print (X)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)
from sklearn import linear_model

      Latitude  Longitude  Depth
0       19.246    145.616  131.6
1        1.863    127.352   80.0
2      -20.579   -173.972   20.0
3      -59.076    -23.557   15.0
4       11.938    126.427   15.0
...        ...        ...    ...
1994   -21.525    -68.318  120.7
1995    -4.869    153.288   47.5
1996    -5.754    153.868   35.0
1997    -4.890    144.508   69.5
1998    -5.567    150.562   10.0

[1999 rows x 3 columns]


In [49]:
regression = linear_model.LinearRegression()
regression.fit(X_train, y_train)
Linear_predictions = regression.predict(X_test)
Linear_predictions

array([6.01078841, 6.0255881 , 6.05731003, 5.99453801, 6.0163912 ,
       5.99330709, 5.99869781, 6.03323857, 5.9943476 , 5.98545441,
       5.98109413, 5.98308994, 5.9872541 , 5.99088381, 6.03210394,
       6.00622426, 6.00852751, 5.99383217, 5.98462705, 5.99145999,
       6.16143335, 5.99793098, 6.04688542, 6.00224338, 5.99353044,
       6.0120605 , 5.9808597 , 5.9944541 , 6.0261902 , 6.0268641 ,
       6.06466915, 5.97962544, 6.0332409 , 6.17747595, 6.0368964 ,
       5.98787118, 6.08852412, 6.01462961, 6.05265157, 5.97978193,
       5.98649138, 6.03415411, 6.07084278, 5.98741369, 6.0827524 ,
       5.99295098, 6.03695576, 5.99593536, 6.07400199, 6.1287339 ,
       6.01283374, 5.9923093 , 5.98521756, 6.03514696, 6.053139  ,
       5.99343649, 6.00873991, 6.01806843, 6.05537293, 6.00801387,
       6.03295646, 6.0149467 , 6.07758748, 6.0129428 , 5.98589633,
       6.16710178, 5.99461025, 6.02798188, 6.04504999, 6.0062167 ,
       6.16829459, 6.04097211, 6.02870951, 5.99096301, 5.97244

In [50]:
regression = linear_model.Lasso(alpha=0.2)
regression.fit(X_train, y_train)
Lasso_predictions = regression.predict(X_test)
Lasso_predictions

array([6.01295506, 6.0215811 , 6.05233528, 6.00023319, 6.02252118,
       5.99908064, 6.00524761, 6.03050964, 6.00009392, 5.99282042,
       5.99464441, 5.99409751, 5.99370379, 5.99786318, 6.02905032,
       6.01053704, 6.0104775 , 5.99961172, 5.99238048, 5.99794794,
       6.15508891, 6.00322444, 6.04023067, 6.00624468, 5.99860247,
       6.01580396, 5.99435943, 5.99974961, 6.02222947, 6.02237067,
       6.05065042, 5.99322159, 6.02792734, 6.16423761, 6.02875903,
       5.99472172, 6.08546161, 6.01414685, 6.04974012, 5.99337835,
       5.99387523, 6.02892253, 6.05728028, 5.99448975, 6.07924963,
       5.99905778, 6.03137469, 6.00269524, 6.06901718, 6.1234376 ,
       6.01290966, 5.99810466, 5.99270597, 6.02849531, 6.0439064 ,
       5.99940623, 6.01063356, 6.0230326 , 6.05419615, 6.00947507,
       6.02687243, 6.01440263, 6.07047452, 6.01469344, 5.99308975,
       6.15798622, 5.99968753, 6.0225926 , 6.04399   , 6.00820965,
       6.1557081 , 6.03388995, 6.02426081, 5.99709788, 5.98734

In [51]:
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(n_estimators = 10, random_state = 0)
regression.fit(X_train, y_train)
RandomForest_predictions = regression.predict(X_test)
RandomForest_predictions

array([5.92 , 6.4  , 6.11 , 5.81 , 5.81 , 6.2  , 6.11 , 5.82 , 5.99 ,
       5.82 , 5.99 , 6.37 , 5.94 , 5.83 , 5.86 , 5.71 , 6.38 , 6.14 ,
       6.19 , 6.   , 6.08 , 5.85 , 6.17 , 6.   , 5.94 , 6.11 , 5.71 ,
       6.18 , 5.75 , 5.9  , 5.88 , 5.74 , 5.99 , 6.21 , 5.85 , 5.77 ,
       6.06 , 5.89 , 5.69 , 5.99 , 5.89 , 5.86 , 5.9  , 5.77 , 6.18 ,
       5.89 , 6.08 , 6.01 , 6.31 , 5.91 , 5.9  , 6.25 , 6.08 , 6.01 ,
       5.79 , 5.79 , 5.96 , 5.69 , 5.87 , 6.12 , 5.78 , 6.14 , 5.93 ,
       5.85 , 5.73 , 6.17 , 6.01 , 5.94 , 6.19 , 6.13 , 6.22 , 6.83 ,
       5.98 , 5.89 , 6.   , 5.76 , 6.18 , 6.12 , 5.7  , 6.34 , 5.74 ,
       5.67 , 6.15 , 6.11 , 6.79 , 6.07 , 5.95 , 6.43 , 6.37 , 5.62 ,
       6.11 , 6.08 , 5.95 , 5.7  , 6.13 , 6.12 , 5.7  , 6.07 , 6.11 ,
       5.89 , 5.99 , 6.26 , 5.97 , 6.18 , 5.79 , 5.85 , 6.27 , 5.87 ,
       6.14 , 5.77 , 6.11 , 6.26 , 5.75 , 6.11 , 6.11 , 6.26 , 5.74 ,
       5.85 , 6.11 , 5.8  , 5.8  , 5.86 , 6.28 , 6.52 , 6.19 , 6.33 ,
       6.12 , 6.07 ,

In [52]:
y_test

405     5.7
1189    5.8
674     6.1
1358    5.7
810     6.3
       ... 
1978    7.8
1980    5.9
384     6.2
1013    7.6
1944    6.1
Name: Magnitude, Length: 200, dtype: float64

In [53]:
from sklearn.metrics import mean_squared_error, r2_score
print (mean_squared_error(y_test, Linear_predictions))
print (mean_squared_error(y_test, Lasso_predictions))
print (mean_squared_error(y_test, RandomForest_predictions))

0.1837512434023585
0.18377055523530023
0.19974112
